package skycampus.v2.eventos;

public enum TipoEvento {
    MISION_ASIGNADA,
    MISION_COMPLETADA,
    SIN_DRONE_DISPONIBLE,
    FALLO_DRONE,
    CLIMA_ADVERSO,
    PAQUETE_EXCEDE_CAPACIDAD,
    URGENTE_SIN_DRONE_RAPIDO
}
